@startuml

actor Empleado

Empleado -- (Alta cliente)
Empleado -- (Introducir pedido)
Empleado -- (Obtener estado pedido)
Empleado -- (Buscar pedido)
Empleado -- (Cancelar pedido)

(Introducir pedido) <.. (Alta cliente) : extiende
(Buscar cliente) <.. (Introducir pedido) : incluye
(Introducir pedido) <.. (Pago con tarjeta) : extiende
(Introducir pedido) <.. (Pago en cuenta) : extiende
(Buscar pedido) <.. (Obtener estado pedido) : incluye
(Buscar pedido) <.. (Cancelar pedido) : incluye


@enduml